SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
-- Transação 1
BEGIN TRAN;

SELECT * FROM FUNCIONARIO;
print 'SELECT concluído em: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);
-- Pausa de 20 segundos
WAITFOR DELAY '00:00:20'
COMMIT TRAN;
print 'COMMIT em: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);

-- Transação 2:
BEGIN TRAN
INSERT INTO FUNCIONARIO (Pnome, Minicial, Unome, Cpf)
VALUES('Herysson', 'R', 'Figueiredo', '0187679808')
PRINT 'INSERT conc´luído em ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);
COMMIT TRAN;
PRINT 'COMMIT em: ' + CONVERT(varchar(30), SYSDATETIME(), 121);